[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_CHAIN_ID = "80001"
  NEXT_PUBLIC_RPC_URL = "https://rpc-mumbai.maticvigil.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
